services:
    ersah.list.service.ga:
        class: Ersah\GABundle\Utils\GAList
        arguments: ['%view_id%','%limit%','%from%','%to%','%sorting%', '%sortby%','%json_key_file%','%dimensions%', '%listMetrics%','%mainMetrics%']
    ersah.main.service.ga:
        class: Ersah\GABundle\Utils\GAMain
        arguments: ['%view_id%','%limit%','%from%','%to%','%sorting%', '%sortby%','%json_key_file%','%dimensions%', '%listMetrics%','%mainMetrics%']
    admin.ga.reports:
        class: Ersah\GABundle\Admin\GAAdmin
        arguments: [~, Ersah\GABundle\Entity\GA, 'ErsahGABundle:GAAdmin']
        tags:
            - { name: sonata.admin, manager_type: orm, label: Google Analytics, on_top: true, group: Google Analytics, icon: '<i class="fa fa-google"></i>' }
    app.twig_extension.date:
        class: Ersah\GABundle\Twig\DateExtension
        public: false
        tags:
            - { name: twig.extension }
    ersah.block.service.ga:
        class: Ersah\GABundle\Block\GABlock
        arguments:
            - ersah.block.service.ga
            - "@templating"
            - '@ersah.main.service.ga'
        tags:
            - { name: sonata.block }